#!/usr/bin/env python

from __future__ import with_statement, print_function
import subprocess
import sys

# don't fill in both of these
select_codes = []
ignore_codes = [
    "E121",
    "E122",
    "E123",
    "E124",
    "E125",
    "E126",
    "E127",
    "E128",
    "E129",
    "E131",
    "E501",
    "W191",
    "E101",
    "E111",
]
# Add things like "--max-line-length=120" below
overrides = []


def main():
    git_args = ['git', '--no-pager', 'diff', '--cached']

    pep8_args = ['pep8', '--diff']
    if select_codes and ignore_codes:
        print(u'Error: select and ignore codes are mutually exclusive')
        sys.exit(1)
    elif select_codes:
        pep8_args.extend(('--select', ','.join(select_codes)))
    elif ignore_codes:
        pep8_args.extend(('--ignore', ','.join(ignore_codes)))
    pep8_args.extend(overrides)
    pep8_args.append('.')

    cmd = ' '.join(git_args) + ' | ' + ' '.join(pep8_args)
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, shell=True)
    output, error = proc.communicate()

    if error:
        print(u'Error in pep8 checking commit', error.decode("utf-8"))
        sys.exit(1)

    if output:
        print(u'PEP8 style violations have been detected.  Please fix them\n'
              'or force the commit with "git commit --no-verify".\n')
        print(output.decode("utf-8"))
        sys.exit(1)


if __name__ == '__main__':
    main()
